parser: '@typescript-eslint/parser'
extends:
    - 'eslint:recommended'
    - 'plugin:react/recommended'
    - 'plugin:@typescript-eslint/recommended'
parserOptions:
    ecmaVersion: 2021
    sourceType: 'module'
    ecmaFeatures:
        jsx: true
    project: './tsconfig.json'
plugins:
    - react
    - react-hooks
    - '@typescript-eslint'
rules:
    react/prop-types: 'off'
    react-hooks/rules-of-hooks: 'error'
    react-hooks/exhaustive-deps: 'warn'
    react/react-in-jsx-scope: 'off'
settings:
    react:
        version: 'detect'
